version: "3.0"

services:
  node-app:
    image: node:8.7.0-alpine
    command: npm start
    volumes:
      - ${WORKDIR}/apps/node-app:/usr/src/app
      - node_modules:/usr/local/lib/node_modules/
    working_dir: /usr/src/app
    environment:
      - NODE_PATH=/usr/local/lib/node_modules/
    ports:
      - "3000:80"
    depends_on:
      - redis

  go-app:
    image: agencyrevolution/go:1.8.4-alpine3.6
    command: go run main.go
    volumes:
      - ${WORKDIR}/apps/go-app:/go/src/app
      - go_base:/go
    working_dir: /go/src/app
    ports:
      - "3001:80"
    depends_on:
      - node-app

  redis:
    image: redis:3.0.6
    ports:
    - "6380:6379"

volumes:
  node_modules:
  go_base:
